### ISSUE TITLE
Rename top level artifact name to deltaforce-parent

### ISSUE THREAD

**Issue by dopsun** [maxns/deltaforce#15]
Currently, artifact name in top level artifact is: `parent`, here is what I'm thinking:
- most of other open source projects, they are using `feature-parent` for top level pom. E.g. [Guava](https://github.com/google/guava/blob/master/pom.xml), [Ignite](https://github.com/apache/ignite/blob/master/pom.xml).
- It creates a top level projects `parent` in Eclipse IDE, which once wrapped up, does not give any clues about what's inside.
- It installs a component in to maven repository, and it's jar is: parent-1.0-SNAPSHOT.pom.

Propose:
- To change the artifact name into `deltaforce-parent`.

**Comment by jasonman107** [comment]
good point, we should do this.
